Insert into student(stud_id,stud_name,dept_name)
Values("1MV16CS001","ABHIJEET","CS");


Insert into student(stud_id,stud_name,dept_name)
Values("student","ABHIJNA","CS");

Insert into student(stud_id,stud_name,dept_name)
Values("1MV16CS003","ABHISHEK DAGAR","CS");

Insert into student(stud_id,stud_name,dept_name)
Values("1MV16CS004","ABHISHEK SINGH","CS");

Insert into student(stud_id,stud_name,dept_name)
Values("1MV16CS005","ADITYA NATARAJ","CS");

Insert into student(stud_id,stud_name,dept_name)
Values("1MV16CS006","ADITYA YADAV","CS");

Insert into student(stud_id,stud_name,dept_name)
Values("1MV16CS007","ADITYA NARAYAN","CS");

Insert into student(stud_id,stud_name,dept_name)
Values("1MV16CS008","AISHVARAYA","CS");

Insert into student(stud_id,stud_name,dept_name)
Values("1MV16CS009","AKSHAY","CS");
