CREATE TRIGGER User_exists BEFORE INSERT ON student 
	REFERENCING NEW ROW AS NEWROW
	FOR EACH ROW WHEN (NEWROW.ID > 100)
BEGIN usrexists
	IF EXISTS (SELECT * FROM student WHERE student.stud_id = NEWROW.stud_id) THEN
 SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'already exists';
	END IF;
END;
/